### ISSUE TITLE
Files exposed as static assets

### ISSUE THREAD

**Issue by telcy** [vercel/hono-starter#1]
Files are not properly excluded and exposed as static assets.

https://hono-starter.vercel.sh/package-lock.json
https://hono-starter.vercel.sh/README.md
https://hono-starter.vercel.sh/tsconfig.json

<img width="1223" alt="Screenshot 2024-07-04 at 21 55 31" src="https://github.com/vercel/hono-starter/assets/3081527/e36641bb-ed74-4a99-9be3-0defa03a7e7c">

**Comment by dan-fein** [comment]
Thank you for raising this, this has been updated with `.vercelignore`.
